version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    command: python main.py
    env_file:
      - env_file
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:12.18-alpine
    ports:
      - "5432:5432"
    env_file:
      - env_file
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3

